version: '3.8'

services:
  python-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aleart-python-backend
    ports:
      - "8000:8000"
    environment:
      # These are automatically loaded from .env file
      - MONGODB_URI=${MONGODB_URI:-}
      - PINATA_JWT=${PINATA_JWT:-}
      - PINATA_API_KEY=${PINATA_API_KEY:-}
      - PINATA_API_SECRET=${PINATA_API_SECRET:-}
    volumes:
      - ./generated_images:/app/generated_images
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G
        reservations:
          cpus: '1'
          memory: 4G

